version: '3'

networks:
  api:
    driver: bridge

services:
  nats:
    image: 'nats'
    ports:
      - "4222:4222"
    networks:
      - api
  pg:
    build:
      dockerfile: Go-auth-service/deployments/DockerfileDb
    ports:
      - "5433:5432"
    networks:
      - api
  pg2:
    build:
      dockerfile: Go-user-service/deployments/DockerfileDb
    ports:
      - "5434:5432"
    networks:
      - api
  pg3:
    build:
      dockerfile: Go-scheduler-service/deployments/DockerfileDb
    ports:
      - "5435:5432"
    networks:
      - api
  go-auth:
    build:
      context: ./Go-auth-service
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=pg
    ports:
      - "8081:8080"
    networks:
      - api
    depends_on:
      - pg
      - nats
  go-users:
    build:
      context: ./Go-user-service
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=pg2
    ports:
      - "8082:8080"
    networks:
      - api
    depends_on:
      - pg2
      - nats
  go-scheduler:
    build:
      context: ./Go-scheduler-service
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=pg3
    ports:
      - "8083:8080"
    networks:
      - api
    depends_on:
      - pg3
